apiVersion: apps/v1
kind: Deployment
metadata:
  name: hellogo
  labels:
    app: hellogo
    version: v1.0.0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hellogo
  template:
    metadata:
      labels:
        app: hellogo
    spec:
      containers:
      - name: hellogo
        image: saphoooo/hellogo:latest
        ports:
        - containerPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: hellogo
spec:
  selector:
    app: hellogo
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: NodePort      